// Generated by purrc — do not edit.
// cheatah-deps: math
#pragma once
#include "cheatah.hpp"
#include "math.hpp"

/**
 * @file color.hpp
 *
 * plot.color — colours, categorical palettes, and continuous colormaps for plotting.
 *
 * `import plot.color as color`.
 *
 * Pure data + interpolation, no device: a Color is four floats in [0, 1]; a categorical palette is
 * a `list<Color>` cycled by series index; a colormap maps t in [0, 1] to a Color by linear
 * interpolation through a small anchor table (the classic perceptual maps ship as anchors). An
 * alpha of exactly 0 is the "auto" sentinel the figure layer resolves to the next palette colour.
 * (The API spec sketched palettes as `ndarray<Color>`; cheatah's ndarray holds numeric fields, so
 * the purr-native `list<Color>` is the honest container.)
 */
namespace cheatah::color {

namespace builtins = ::cheatah::builtins;
namespace math = ::cheatah::math;

/**
 * One RGBA colour, channels in [0, 1]. Alpha exactly 0 means "auto: take the next palette colour".
 */
struct Color {
    double r;
    double g;
    double b;
    double a;
    void cheatah_pretty_print(std::ostream& os_, long long indent_) const {
        os_ << "Color(\n";
        os_ << std::string(indent_ + 4, ' ') << "r = ";
        os_ << this->r;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "g = ";
        os_ << this->g;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "b = ";
        os_ << this->b;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "a = ";
        os_ << this->a;
        os_ << "\n";
        os_ << std::string(indent_, ' ') << ")";
    }
};
inline std::ostream& operator<<(std::ostream& os_, const Color& v_) {
    return os_ << "Color(" << "r=" << v_.r << ", g=" << v_.g << ", b=" << v_.b << ", a=" << v_.a << ")";
}

/**
 * An opaque colour from red/green/blue channels.
 *
 * @param r red in [0, 1].
 * @param g green in [0, 1].
 * @param b blue in [0, 1].
 * @return the opaque Color (alpha 1).
 * @complexity O(1).
 * @alloc the Color.
 * @systest systests/test_color.purr
 */
inline Color rgb(builtins::Value auto&& r, builtins::Value auto&& g, builtins::Value auto&& b) {
    return Color{.r = static_cast<double>(r), .g = static_cast<double>(g), .b = static_cast<double>(b), .a = static_cast<double>(1.0)};
}


/**
 * A colour from all four channels. Note alpha exactly 0 is reserved as the auto sentinel — a fully
 * transparent DRAWN colour is not representable (use a tiny alpha instead; nothing visible changes).
 *
 * @param r red in [0, 1].
 * @param g green in [0, 1].
 * @param b blue in [0, 1].
 * @param a alpha in [0, 1].
 * @return the Color.
 * @complexity O(1).
 * @alloc the Color.
 * @systest systests/test_color.purr
 */
inline Color rgba(builtins::Value auto&& r, builtins::Value auto&& g, builtins::Value auto&& b, builtins::Value auto&& a) {
    return Color{.r = static_cast<double>(r), .g = static_cast<double>(g), .b = static_cast<double>(b), .a = static_cast<double>(a)};
}


/**
 * The "auto" colour sentinel: alpha 0. A Series carrying it gets the next palette colour when the
 * figure resolves styles.
 *
 * @return the transparent auto sentinel.
 * @complexity O(1).
 * @alloc the Color.
 * @systest systests/test_color.purr
 */
inline Color auto_color() {
    return Color{.r = static_cast<double>(0.0), .g = static_cast<double>(0.0), .b = static_cast<double>(0.0), .a = static_cast<double>(0.0)};
}


/**
 * Whether @p c is the auto sentinel (alpha exactly 0) — the test the figure layer runs before
 * assigning palette colours.
 *
 * @param c the colour to inspect.
 * @return true when @p c means "auto".
 * @complexity O(1).
 * @alloc none.
 * @systest systests/test_color.purr
 */
inline bool is_auto(builtins::Value auto&& c) {
    return (c.a == 0.0);
}


/**
 * Linear interpolation between two colours, channel-wise (alpha included), with @p t clamped to
 * [0, 1] — the primitive every colormap is built from.
 *
 * @param c0 the colour at t = 0.
 * @param c1 the colour at t = 1.
 * @param t the blend position (clamped to [0, 1]).
 * @return the blended Color.
 * @complexity O(1).
 * @alloc the Color.
 * @systest systests/test_color.purr
 */
inline Color lerp(builtins::Value auto&& c0, builtins::Value auto&& c1, builtins::Value auto&& t) {
    auto u = t;
    if ((u < 0.0)) {
        u = 0.0;
    }
    if ((u > 1.0)) {
        u = 1.0;
    }
    return Color{
        .r = static_cast<double>((c0.r + ((c1.r - c0.r) * u))),
        .g = static_cast<double>((c0.g + ((c1.g - c0.g) * u))),
        .b = static_cast<double>((c0.b + ((c1.b - c0.b) * u))),
        .a = static_cast<double>((c0.a + ((c1.a - c0.a) * u)))
    };
}


/**
 * Sample an anchor table at @p t in [0, 1]: the anchors are treated as evenly spaced stops and the
 * two neighbours of @p t are blended. Out-of-range @p t clamps; an empty table returns opaque black.
 *
 * @param anchors the colour stops, evenly spaced across [0, 1].
 * @param t the sample position (clamped to [0, 1]).
 * @return the interpolated Color.
 * @complexity O(1).
 * @alloc the Color.
 * @systest systests/test_color.purr
 */
inline Color sample(builtins::Value auto&& anchors, builtins::Value auto&& t) {
    auto n = builtins::len(anchors);
    if ((n == 0LL)) {
        return rgb(0.0, 0.0, 0.0);
    }
    if ((n == 1LL)) {
        return builtins::index(anchors, 0LL);
    }
    auto u = t;
    if ((u < 0.0)) {
        u = 0.0;
    }
    if ((u > 1.0)) {
        u = 1.0;
    }
    auto pos = (u * builtins::to_float((n - 1LL)));
    auto i = builtins::to_int(math::floor(pos));
    if ((i >= (n - 1LL))) {
        return builtins::index(anchors, (n - 1LL));
    }
    return lerp(builtins::index(anchors, i), builtins::index(anchors, (i + 1LL)), (pos - builtins::to_float(i)));
}


/**
 * The viridis colormap (dark violet -> teal -> yellow), sampled at @p t — perceptually uniform and
 * colour-blind friendly; the default for continuous data.
 *
 * @param t the sample position in [0, 1] (clamped).
 * @return the Color at @p t.
 * @complexity O(1).
 * @alloc the Color (plus the transient anchor table).
 * @systest systests/test_color.purr
 */
inline Color viridis(builtins::Value auto&& t) {
    std::vector<Color> anchors;
    builtins::append(anchors, rgb(0.267, 0.005, 0.329));
    builtins::append(anchors, rgb(0.231, 0.322, 0.545));
    builtins::append(anchors, rgb(0.129, 0.567, 0.549));
    builtins::append(anchors, rgb(0.369, 0.788, 0.384));
    builtins::append(anchors, rgb(0.993, 0.906, 0.144));
    return sample(anchors, t);
}


/**
 * The magma colormap (black -> purple -> orange -> pale yellow), sampled at @p t.
 *
 * @param t the sample position in [0, 1] (clamped).
 * @return the Color at @p t.
 * @complexity O(1).
 * @alloc the Color (plus the transient anchor table).
 * @systest systests/test_color.purr
 */
inline Color magma(builtins::Value auto&& t) {
    std::vector<Color> anchors;
    builtins::append(anchors, rgb(0.001, 0.000, 0.016));
    builtins::append(anchors, rgb(0.316, 0.071, 0.485));
    builtins::append(anchors, rgb(0.716, 0.215, 0.475));
    builtins::append(anchors, rgb(0.987, 0.535, 0.382));
    builtins::append(anchors, rgb(0.988, 0.998, 0.749));
    return sample(anchors, t);
}


/**
 * The coolwarm diverging colormap (blue -> pale grey -> red), sampled at @p t — for data with a
 * meaningful midpoint (deviations, correlations).
 *
 * @param t the sample position in [0, 1] (clamped).
 * @return the Color at @p t.
 * @complexity O(1).
 * @alloc the Color (plus the transient anchor table).
 * @systest systests/test_color.purr
 */
inline Color coolwarm(builtins::Value auto&& t) {
    std::vector<Color> anchors;
    builtins::append(anchors, rgb(0.230, 0.299, 0.754));
    builtins::append(anchors, rgb(0.865, 0.865, 0.865));
    builtins::append(anchors, rgb(0.706, 0.016, 0.150));
    return sample(anchors, t);
}


/**
 * The 10-colour categorical palette series colours cycle through (the familiar matplotlib-style
 * tab10 wheel: blue, orange, green, red, violet, brown, pink, grey, olive, cyan).
 *
 * @return the 10 opaque categorical colours, in cycling order.
 * @complexity O(1).
 * @alloc the returned list.
 * @systest systests/test_color.purr
 */
inline std::vector<Color> tab10() {
    std::vector<Color> p;
    builtins::append(p, rgb(0.122, 0.467, 0.706));
    builtins::append(p, rgb(1.000, 0.498, 0.055));
    builtins::append(p, rgb(0.173, 0.627, 0.173));
    builtins::append(p, rgb(0.839, 0.153, 0.157));
    builtins::append(p, rgb(0.580, 0.404, 0.741));
    builtins::append(p, rgb(0.549, 0.337, 0.294));
    builtins::append(p, rgb(0.890, 0.467, 0.761));
    builtins::append(p, rgb(0.498, 0.498, 0.498));
    builtins::append(p, rgb(0.737, 0.741, 0.133));
    builtins::append(p, rgb(0.090, 0.745, 0.812));
    return p;
}


/**
 * A categorical palette by name: "tab10" (default) or "dark" (tab10 darkened for light
 * backgrounds). Unknown names return tab10 — a plot always gets usable colours.
 *
 * @param name the palette name.
 * @return the palette colours, in cycling order.
 * @complexity O(1).
 * @alloc the returned list.
 * @systest systests/test_color.purr
 */
inline std::vector<Color> palette(builtins::Value auto&& name) {
    if ((name == std::string("dark"))) {
        auto base = tab10();
        std::vector<Color> p;
        for (long long i = 0; i < builtins::len(base); ++i) {
            auto c = builtins::index(base, i);
            builtins::append(p, rgb((c.r * 0.72), (c.g * 0.72), (c.b * 0.72)));
        }
        return p;
    }
    return tab10();
}


/**
 * A colour from a small CSS-style name table (the everyday names: black, white, red, green, blue,
 * orange, purple, brown, pink, gray, cyan, magenta, gold, teal, steelblue, crimson, forestgreen,
 * darkorange, royalblue, tomato, slategray). Unknown names return opaque black.
 *
 * @param name the colour name (lowercase).
 * @return the named Color (opaque black when unknown).
 * @complexity O(1).
 * @alloc the Color.
 * @systest systests/test_color.purr
 */
inline Color named(builtins::Value auto&& name) {
    if ((name == std::string("white"))) {
        return rgb(1.0, 1.0, 1.0);
    }
    if ((name == std::string("red"))) {
        return rgb(1.0, 0.0, 0.0);
    }
    if ((name == std::string("green"))) {
        return rgb(0.0, 0.502, 0.0);
    }
    if ((name == std::string("blue"))) {
        return rgb(0.0, 0.0, 1.0);
    }
    if ((name == std::string("orange"))) {
        return rgb(1.0, 0.647, 0.0);
    }
    if ((name == std::string("purple"))) {
        return rgb(0.502, 0.0, 0.502);
    }
    if ((name == std::string("brown"))) {
        return rgb(0.647, 0.165, 0.165);
    }
    if ((name == std::string("pink"))) {
        return rgb(1.0, 0.753, 0.796);
    }
    if ((name == std::string("gray"))) {
        return rgb(0.502, 0.502, 0.502);
    }
    if ((name == std::string("cyan"))) {
        return rgb(0.0, 1.0, 1.0);
    }
    if ((name == std::string("magenta"))) {
        return rgb(1.0, 0.0, 1.0);
    }
    if ((name == std::string("gold"))) {
        return rgb(1.0, 0.843, 0.0);
    }
    if ((name == std::string("teal"))) {
        return rgb(0.0, 0.502, 0.502);
    }
    if ((name == std::string("steelblue"))) {
        return rgb(0.275, 0.510, 0.706);
    }
    if ((name == std::string("crimson"))) {
        return rgb(0.863, 0.078, 0.235);
    }
    if ((name == std::string("forestgreen"))) {
        return rgb(0.133, 0.545, 0.133);
    }
    if ((name == std::string("darkorange"))) {
        return rgb(1.0, 0.549, 0.0);
    }
    if ((name == std::string("royalblue"))) {
        return rgb(0.255, 0.412, 0.882);
    }
    if ((name == std::string("tomato"))) {
        return rgb(1.0, 0.388, 0.278);
    }
    if ((name == std::string("slategray"))) {
        return rgb(0.439, 0.502, 0.565);
    }
    return rgb(0.0, 0.0, 0.0);
}


/// ABI/identity marker for the `color` cheatah module: returns the module name.
///
/// Auto-emitted by purrc's library emitter. It is the concrete symbol that
/// anchors the module's signed static archive in opaque (source-hidden) builds.
/// @return the module name (`"color"`).
inline const char* module_abi() noexcept { return "color"; }

}  // namespace cheatah::color

// Re-exported under the host namespace (--reexport cheatah::plot):
namespace cheatah::plot { namespace color = ::cheatah::color; }
