// Generated by purrc — do not edit.
// cheatah-deps: math ndarray
#pragma once
#include "cheatah.hpp"
#include "math.hpp"
#include "ndarray.hpp"

/**
 * @file scale.hpp
 *
 * plot.scale — the pure geometry of a plot: data ranges, "nice" axis ticks, and the data→pixel map.
 *
 * `import plot.scale as scale`.
 *
 * This is the GPU-FREE core of plotting — statically-typed cheatah, no window, no device — so it is
 * fully testable on any machine (cheatah-plot's analog of cheatah-gpu's gpu.dispatch seed). The renderer
 * and figure API are built on top of it: an axis turns raw data into a Range, chooses round "nice" tick
 * positions a human reads at a glance, and maps a data value to a pixel coordinate.
 */
namespace cheatah::scale {

namespace builtins = ::cheatah::builtins;
namespace math = ::cheatah::math;
namespace ndarray = ::cheatah::ndarray;

/**
 * A closed data interval [lo, hi] on one axis.
 */
struct Range {
    double lo;
    double hi;
    void cheatah_pretty_print(std::ostream& os_, long long indent_) const {
        os_ << "Range(\n";
        os_ << std::string(indent_ + 4, ' ') << "lo = ";
        os_ << this->lo;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "hi = ";
        os_ << this->hi;
        os_ << "\n";
        os_ << std::string(indent_, ' ') << ")";
    }
};
inline std::ostream& operator<<(std::ostream& os_, const Range& v_) {
    return os_ << "Range(" << "lo=" << v_.lo << ", hi=" << v_.hi << ")";
}

/**
 * The [min, max] span of a data series, widened to a non-degenerate interval so a flat series still gets
 * a sane axis (all-equal values -> a unit interval centered on the value; empty -> [0, 1]).
 *
 * @param values the data series.
 * @return the data Range (always hi > lo).
 * @complexity O(n).
 * @alloc the Range.
 * @systest systests/test_scale.purr
 * @par Example
 * @code{.purr}
 * import plot.scale as scale
 * import ndarray
 * let values = ndarray.array([3.2, 7.9, 5.1, 4.4])
 * let r = scale.data_range(values)   # -> Range 3.2 .. 7.9, ready for ticks()
 * @endcode
 */
inline Range data_range(::cheatah::ndarray::basic_ndarray<double>& values) {
    auto n = ndarray::size_of(values);
    if ((n == 0LL)) {
        return Range{.lo = static_cast<double>(0.0), .hi = static_cast<double>(1.0)};
    }
    auto lo = builtins::index(values, 0LL);
    auto hi = builtins::index(values, 0LL);
    for (long long i = 1LL; i < n; ++i) {
        auto v = builtins::index(values, i);
        if ((v < lo)) {
            lo = v;
        }
        if ((v > hi)) {
            hi = v;
        }
    }
    if ((hi <= lo)) {
        return Range{.lo = static_cast<double>((lo - 0.5)), .hi = static_cast<double>((lo + 0.5))};
    }
    return Range{.lo = static_cast<double>(lo), .hi = static_cast<double>(hi)};
}


/**
 * A "nice" tick step — 1, 2, or 5 times a power of ten — for about @p target ticks across @p span, so
 * gridlines land on round numbers. The classic axis-labelling choice.
 *
 * @param span the axis span (hi - lo); must be > 0.
 * @param target the desired tick count (approximate; must be >= 1).
 * @return the nice step size (> 0).
 * @complexity O(1).
 * @alloc none.
 * @systest systests/test_scale.purr
 * @par Example
 * @code{.purr}
 * import plot.scale as scale
 * let r = scale.Range({.lo = 0.0, .hi = 7.3})
 * let step = scale.nice_step(r.hi - r.lo, 6)   # -> 1.0: gridlines land on whole numbers
 * @endcode
 */
inline double nice_step(builtins::Value auto&& span, builtins::Value auto&& target) {
    auto raw = builtins::truediv(span, builtins::to_float(target));
    auto magnitude = math::pow(10.0, math::floor(math::log10(raw)));
    auto residual = builtins::truediv(raw, magnitude);
    auto nice = 10.0;
    if ((residual < 1.5)) {
        nice = 1.0;
    } else {
        if ((residual < 3.0)) {
            nice = 2.0;
        } else {
            if ((residual < 7.0)) {
                nice = 5.0;
            }
        }
    }
    return (nice * magnitude);
}


/**
 * The ascending tick positions across @p r on a nice step — the round values gridlines and labels sit on.
 *
 * @param r the axis data range.
 * @param target the desired tick count (approximate; must be >= 1).
 * @return the ascending tick positions within [r.lo, r.hi] (at least one).
 * @complexity O(ticks).
 * @alloc the returned tick array.
 * @systest systests/test_scale.purr
 * @par Example
 * @code{.purr}
 * import plot.scale as scale
 * let r = scale.Range({.lo = 0.0, .hi = 7.3})
 * let t = scale.ticks(r, 6)   # -> [0, 1, 2, 3, 4, 5, 6, 7]
 * @endcode
 */
inline ::cheatah::ndarray::basic_ndarray<double> ticks(builtins::Value auto&& r, builtins::Value auto&& target) {
    auto span = (r.hi - r.lo);
    if ((span <= 0.0)) {
        auto single = ndarray::zeros(std::vector{1LL});
        single[0LL] = r.lo;
        return single;
    }
    auto step = nice_step(span, target);
    auto first = (math::ceil(builtins::truediv(r.lo, step)) * step);
    auto guard = (r.hi + (step * 0.0001));
    auto count = 0LL;
    auto t = first;
    while ((t <= guard)) {
        count += 1LL;
        t += step;
    }
    auto out = ndarray::zeros(std::vector{count});
    auto k = 0LL;
    t = first;
    while ((k < count)) {
        out[k] = t;
        k += 1LL;
        t += step;
    }
    return out;
}


/**
 * The ascending tick positions for a LOG axis across @p r — decade marks (powers of ten), strided
 * when the range spans more decades than @p target, and subdivided with the 1-2-5 mantissas when it
 * spans fewer than two so short log axes still read well. Sub-decade ranges that trap no 1-2-5
 * mantissa fall back to linear ticks (the honest choice — log labelling adds nothing there).
 *
 * @param r the axis data range; a log axis holds positive data, so r.lo must be > 0 (a
 *          non-positive or degenerate range falls back exactly like `ticks`).
 * @param target the desired tick count (approximate; must be >= 1).
 * @return the ascending tick positions within [r.lo, r.hi] (at least one).
 * @complexity O(ticks).
 * @alloc the returned tick array.
 * @systest systests/test_scale.purr
 * @par Example
 * @code{.purr}
 * import plot.scale as scale
 * let r = scale.Range({.lo = 1.0, .hi = 10000.0})
 * let t = scale.log_ticks(r, 5)   # -> [1, 10, 100, 1000, 10000]: decade marks
 * @endcode
 */
inline ::cheatah::ndarray::basic_ndarray<double> log_ticks(builtins::Value auto&& r, builtins::Value auto&& target) {
    if ((r.lo <= 0.0)) {
        return ticks(r, target);
    }
    auto span = (r.hi - r.lo);
    if ((span <= 0.0)) {
        return ticks(r, target);
    }
    auto d_lo = builtins::to_int(math::ceil((math::log10(r.lo) - 0.0001)));
    auto d_hi = builtins::to_int(math::floor((math::log10(r.hi) + 0.0001)));
    auto decades = ((d_hi - d_lo) + 1LL);
    if ((decades >= 2LL)) {
        auto stride = 1LL;
        if ((decades > target)) {
            stride = builtins::floordiv(((decades + target) - 1LL), target);
        }
        auto count = builtins::floordiv(((decades + stride) - 1LL), stride);
        auto out = ndarray::zeros(std::vector{count});
        auto k = 0LL;
        while ((k < count)) {
            out[k] = math::pow(10.0, builtins::to_float((d_lo + (k * stride))));
            k += 1LL;
        }
        return out;
    }
    auto base_lo = builtins::to_int(math::floor((math::log10(r.lo) + 0.0001)));
    auto base_hi = builtins::to_int(math::floor((math::log10(r.hi) + 0.0001)));
    auto guard_lo = (r.lo * 0.9999);
    auto guard_hi = (r.hi * 1.0001);
    auto count = 0LL;
    for (long long d = base_lo; d < (base_hi + 1LL); ++d) {
        auto decade = math::pow(10.0, builtins::to_float(d));
        if ((decade >= guard_lo)) {
            if ((decade <= guard_hi)) {
                count += 1LL;
            }
        }
        if (((2.0 * decade) >= guard_lo)) {
            if (((2.0 * decade) <= guard_hi)) {
                count += 1LL;
            }
        }
        if (((5.0 * decade) >= guard_lo)) {
            if (((5.0 * decade) <= guard_hi)) {
                count += 1LL;
            }
        }
    }
    if ((count == 0LL)) {
        return ticks(r, target);
    }
    auto out = ndarray::zeros(std::vector{count});
    auto k = 0LL;
    for (long long d = base_lo; d < (base_hi + 1LL); ++d) {
        auto decade = math::pow(10.0, builtins::to_float(d));
        if ((decade >= guard_lo)) {
            if ((decade <= guard_hi)) {
                out[k] = decade;
                k += 1LL;
            }
        }
        if (((2.0 * decade) >= guard_lo)) {
            if (((2.0 * decade) <= guard_hi)) {
                out[k] = (2.0 * decade);
                k += 1LL;
            }
        }
        if (((5.0 * decade) >= guard_lo)) {
            if (((5.0 * decade) <= guard_hi)) {
                out[k] = (5.0 * decade);
                k += 1LL;
            }
        }
    }
    return out;
}


/**
 * Map a data value to a pixel coordinate: linearly from the data range @p r onto the pixel span
 * [@p px_lo, @p px_hi]. (For a screen Y axis, pass px_lo/px_hi flipped so larger data is higher up.)
 *
 * @param value the data value to place.
 * @param r the axis data range.
 * @param px_lo the pixel coordinate of r.lo.
 * @param px_hi the pixel coordinate of r.hi.
 * @return the pixel coordinate of @p value (not clamped to the span).
 * @complexity O(1).
 * @alloc none.
 * @systest systests/test_scale.purr
 * @par Example
 * @code{.purr}
 * import plot.scale as scale
 * let r = scale.Range({.lo = 0.0, .hi = 10.0})
 * let px = scale.to_pixel(2.5, r, 0.0, 800.0)   # -> 200.0
 * let py = scale.to_pixel(2.5, r, 600.0, 0.0)   # -> 450.0: flipped span for screen Y
 * @endcode
 */
inline double to_pixel(builtins::Value auto&& value, builtins::Value auto&& r, builtins::Value auto&& px_lo, builtins::Value auto&& px_hi) {
    auto span = (r.hi - r.lo);
    if ((span <= 0.0)) {
        return px_lo;
    }
    return (px_lo + (builtins::truediv((value - r.lo), span) * (px_hi - px_lo)));
}


/**
 * Map a data value to a pixel coordinate on a LOG axis: linear in log10 space across @p r, onto the
 * pixel span [@p px_lo, @p px_hi]. Non-positive ranges or values fall back to the linear map — a log
 * axis holds positive data, and the figure layer keeps it that way; the fallback just refuses to NaN.
 *
 * @param value the data value to place (> 0 on a real log axis).
 * @param r the axis data range (both ends > 0 on a real log axis).
 * @param px_lo the pixel coordinate of r.lo.
 * @param px_hi the pixel coordinate of r.hi.
 * @return the pixel coordinate of @p value (not clamped to the span).
 * @complexity O(1).
 * @alloc none.
 * @systest systests/test_scale.purr
 * @par Example
 * @code{.purr}
 * import plot.scale as scale
 * let r = scale.Range({.lo = 1.0, .hi = 1000.0})
 * let px = scale.to_pixel_log(10.0, r, 0.0, 900.0)   # -> 300.0: one decade of three
 * @endcode
 */
inline double to_pixel_log(builtins::Value auto&& value, builtins::Value auto&& r, builtins::Value auto&& px_lo, builtins::Value auto&& px_hi) {
    if ((r.lo <= 0.0)) {
        return to_pixel(value, r, px_lo, px_hi);
    }
    if ((r.hi <= 0.0)) {
        return to_pixel(value, r, px_lo, px_hi);
    }
    if ((value <= 0.0)) {
        return to_pixel(value, r, px_lo, px_hi);
    }
    auto llo = math::log10(r.lo);
    auto lhi = math::log10(r.hi);
    auto span = (lhi - llo);
    if ((span <= 0.0)) {
        return px_lo;
    }
    return (px_lo + (builtins::truediv((math::log10(value) - llo), span) * (px_hi - px_lo)));
}


/// ABI/identity marker for the `scale` cheatah module: returns the module name.
///
/// Auto-emitted by purrc's library emitter. It is the concrete symbol that
/// anchors the module's signed static archive in opaque (source-hidden) builds.
/// @return the module name (`"scale"`).
inline const char* module_abi() noexcept { return "scale"; }

}  // namespace cheatah::scale

// Re-exported under the host namespace (--reexport cheatah::plot):
namespace cheatah::plot { namespace scale = ::cheatah::scale; }
