// Generated by purrc — do not edit.
// cheatah-deps: math ndarray plot
#pragma once
#include "cheatah.hpp"
#include "math.hpp"
#include "ndarray.hpp"
#include "plot.hpp"

/**
 * @file figure.hpp
 *
 * plot.figure — the figure model: subplots, axes, and the fluent building API.
 *
 * `import plot.figure as figure`.
 *
 * A Figure is plain data — a grid of Subplots, each holding axes and a series list — built by
 * free functions that RETURN A MODIFIED COPY (cheatah values are const; the fluent style is
 * `let f = figure.line(figure.new_figure(), x, y)` or a pipeline of rebindings). The renderer
 * consumes the finished value; nothing here touches a device. Axis limits are `math.nan` until
 * set — NaN means "auto: compute from the data at render time".
 */
namespace cheatah::figure {

namespace builtins = ::cheatah::builtins;
namespace math = ::cheatah::math;
namespace ndarray = ::cheatah::ndarray;
namespace plot = ::cheatah::plot;
using ::cheatah::plot::series::Series;
using ::cheatah::plot::color::Color;

/**
 * An axis transform choice ("linear" or "log") — a tiny struct instead of an enum, per the
 * house style; make one with `linear()` / `log_scale()`.
 */
struct Scale {
    std::string kind;
    void cheatah_pretty_print(std::ostream& os_, long long indent_) const {
        os_ << "Scale(\n";
        os_ << std::string(indent_ + 4, ' ') << "kind = ";
        os_ << this->kind;
        os_ << "\n";
        os_ << std::string(indent_, ' ') << ")";
    }
};
inline std::ostream& operator<<(std::ostream& os_, const Scale& v_) {
    return os_ << "Scale(" << "kind=" << v_.kind << ")";
}

/**
 * One axis: label, transform, limits, and a target tick count. NaN limits mean "auto from data".
 */
struct Axis {
    std::string label;
    Scale scale;
    double lo{};
    double hi{};
    long long ticks{};
    void cheatah_pretty_print(std::ostream& os_, long long indent_) const {
        os_ << "Axis(\n";
        os_ << std::string(indent_ + 4, ' ') << "label = ";
        os_ << this->label;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "scale = ";
        this->scale.cheatah_pretty_print(os_, indent_ + 4);
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "lo = ";
        os_ << this->lo;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "hi = ";
        os_ << this->hi;
        os_ << ",\n";
        os_ << std::string(indent_ + 4, ' ') << "ticks = ";
        os_ << this->ticks;
        os_ << "\n";
        os_ << std::string(indent_, ' ') << ")";
    }
};
inline std::ostream& operator<<(std::ostream& os_, const Axis& v_) {
    return os_ << "Axis(" << "label=" << v_.label << ", scale=" << v_.scale << ", lo=" << v_.lo << ", hi=" << v_.hi << ", ticks=" << v_.ticks << ")";
}

/**
 * One cell of the figure grid: a title, two axes, the series drawn in it, and a legend flag.
 */
struct Subplot {
    std::string title;
    Axis x;
    Axis y;
    std::vector<Series> series;
    bool legend{};
};

/**
 * The whole figure: a rows×cols grid of subplots, pixel size, the categorical palette, and the
 * index fluent calls currently target.
 */
struct Figure {
    std::vector<Subplot> subplots;
    long long rows{};
    long long cols{};
    long long cur{};
    long long width{};
    long long height{};
    std::vector<Color> palette;
};

/**
 * The linear axis transform (the default).
 *
 * @return the linear Scale.
 * @complexity O(1).
 * @alloc the Scale.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * let s = figure.linear()
 * f = figure.xscale(f, s)   # -> back to the default linear x transform
 * @endcode
 */
inline Scale linear() {
    return Scale{.kind = static_cast<std::string>(std::string("linear"))};
}


/**
 * The log10 axis transform (positive data; ticks land on decades via plot.scale.log_ticks).
 *
 * @return the log Scale.
 * @complexity O(1).
 * @alloc the Scale.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * let s = figure.log_scale()
 * f = figure.yscale(f, s)   # -> the classic semilog-y view
 * @endcode
 */
inline Scale log_scale() {
    return Scale{.kind = static_cast<std::string>(std::string("log"))};
}


/**
 * A fresh default axis: no label, linear, auto limits, 6 ticks — the one place axis defaults live.
 *
 * @return the default Axis.
 * @complexity O(1).
 * @alloc the Axis.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let ax = figure.default_axis()
 * let target = ax.ticks   # -> 6: unlabeled, linear, auto limits
 * @endcode
 */
inline Axis default_axis() {
    return Axis{.label = static_cast<std::string>(std::string("")), .scale = static_cast<Scale>(linear()), .lo = static_cast<double>(math::nan), .hi = static_cast<double>(math::nan), .ticks = 6LL};
}


/**
 * A rows×cols grid figure with empty subplots, 900×600 pixels, the tab10 palette, targeting
 * cell 0 — `new_figure()` is this with a 1×1 grid.
 *
 * @param rows the grid rows (clamped up to at least 1).
 * @param cols the grid columns (clamped up to at least 1).
 * @return the empty grid Figure.
 * @complexity O(rows·cols).
 * @alloc the Figure and its subplots.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0])
 * let y = ndarray.array([1.0, 4.0, 2.0])
 * let f = figure.grid(2, 2)
 * f = figure.subplot(f, 0, 1)
 * f = figure.line(f, x, y)   # -> the line lands in the top-right cell
 * @endcode
 */
inline Figure grid(builtins::Value auto&& rows, builtins::Value auto&& cols) {
    auto r = rows;
    if (r < 1LL) {
        r = 1LL;
    }
    auto c = cols;
    if (c < 1LL) {
        c = 1LL;
    }
    std::vector<Subplot> subs;
    for (long long i = 0; i < (r * c); ++i) {
        std::vector<Series> empty;
        builtins::append(subs, Subplot{
    .title = static_cast<std::string>(std::string("")),
    .x = static_cast<Axis>(default_axis()),
    .y = static_cast<Axis>(default_axis()),
    .series = static_cast<std::vector<Series>>(empty),
    .legend = static_cast<bool>(false)
});
    }
    return Figure{
        .subplots = static_cast<std::vector<Subplot>>(subs),
        .rows = static_cast<long long>(r),
        .cols = static_cast<long long>(c),
        .cur = 0LL,
        .width = 900LL,
        .height = 600LL,
        .palette = static_cast<std::vector<Color>>(plot::color::tab10())
    };
}


/**
 * A fresh single-subplot figure — the usual starting point.
 *
 * @return the empty 1×1 Figure.
 * @complexity O(1).
 * @alloc the Figure.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0, 3.0])
 * let y = ndarray.array([0.0, 1.0, 4.0, 9.0])
 * let f = figure.new_figure()
 * f = figure.line(f, x, y)   # -> a 1x1 figure holding one line series
 * @endcode
 */
inline Figure new_figure() {
    return grid(1LL, 1LL);
}


/**
 * Point fluent calls at grid cell (@p r, @p c) — out-of-range coordinates clamp to the grid.
 *
 * @param f the figure.
 * @param r the target row (0-based).
 * @param c the target column (0-based).
 * @return a copy of @p f targeting that cell.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let data = ndarray.array([1.0, 2.0, 2.0, 3.0, 3.0, 3.0])
 * let f = figure.grid(1, 2)
 * f = figure.subplot(f, 0, 1)
 * f = figure.hist(f, data, 3)   # -> the histogram fills the right-hand cell
 * @endcode
 */
inline Figure subplot(builtins::Value auto&& f, builtins::Value auto&& r, builtins::Value auto&& c) {
    auto g = f;
    auto rr = r;
    if (rr < 0LL) {
        rr = 0LL;
    }
    if (rr >= g.rows) {
        rr = (g.rows - 1LL);
    }
    auto cc = c;
    if (cc < 0LL) {
        cc = 0LL;
    }
    if (cc >= g.cols) {
        cc = (g.cols - 1LL);
    }
    g.cur = ((rr * g.cols) + cc);
    return g;
}


/**
 * Append a pre-built series to the targeted subplot — the bridge between the constructor style
 * (`series.line(x, y)`) and the fluent style.
 *
 * @param f the figure.
 * @param s the series to append.
 * @return a copy of @p f with @p s appended to the current subplot.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import plot.series as series
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0])
 * let y = ndarray.array([2.0, 1.0, 3.0])
 * let s = series.scatter(x, y)
 * let f = figure.new_figure()
 * f = figure.add(f, s)   # -> the pre-built scatter joins the current subplot
 * @endcode
 */
inline Figure add(builtins::Value auto&& f, builtins::Value auto&& s) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    builtins::append(sp.series, s);
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Fluent line mark: append `series.line(x, y)` to the targeted subplot.
 *
 * @param f the figure.
 * @param x the x positions.
 * @param y the y values (same length).
 * @return a copy of @p f with the line appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0, 3.0])
 * let y = ndarray.array([0.0, 1.0, 4.0, 9.0])
 * let f = figure.new_figure()
 * f = figure.line(f, x, y)   # -> one line mark in the single subplot
 * @endcode
 */
inline Figure line(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y) {
    return add(f, plot::series::line(x, y));
}


/**
 * Fluent scatter mark: append `series.scatter(x, y)` to the targeted subplot.
 *
 * @param f the figure.
 * @param x the x positions.
 * @param y the y values (same length).
 * @return a copy of @p f with the scatter appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([1.0, 2.0, 3.0, 4.0])
 * let y = ndarray.array([2.1, 3.9, 6.2, 7.8])
 * let f = figure.new_figure()
 * f = figure.scatter(f, x, y)   # -> circle markers in the single subplot
 * @endcode
 */
inline Figure scatter(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y) {
    return add(f, plot::series::scatter(x, y));
}


/**
 * Fluent bar mark: append `series.bar(x, y)` to the targeted subplot.
 *
 * @param f the figure.
 * @param x the bar positions.
 * @param y the bar heights (same length).
 * @return a copy of @p f with the bars appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0])
 * let counts = ndarray.array([4.0, 7.0, 2.0])
 * let f = figure.new_figure()
 * f = figure.bar(f, x, counts)   # -> three vertical bars
 * @endcode
 */
inline Figure bar(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y) {
    return add(f, plot::series::bar(x, y));
}


/**
 * Fluent area mark: append `series.area(x, y)` to the targeted subplot.
 *
 * @param f the figure.
 * @param x the x positions.
 * @param y the top edge values (same length).
 * @return a copy of @p f with the area appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0, 3.0])
 * let y = ndarray.array([0.5, 1.5, 1.0, 2.0])
 * let f = figure.new_figure()
 * f = figure.area(f, x, y)   # -> the filled area under the curve
 * @endcode
 */
inline Figure area(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y) {
    return add(f, plot::series::area(x, y));
}


/**
 * Fluent step mark: append `series.step(x, y)` to the targeted subplot.
 *
 * @param f the figure.
 * @param x the x positions.
 * @param y the y values (same length).
 * @return a copy of @p f with the step line appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0, 3.0])
 * let y = ndarray.array([1.0, 3.0, 2.0, 2.5])
 * let f = figure.new_figure()
 * f = figure.step(f, x, y)   # -> a hold-until-next-x step line
 * @endcode
 */
inline Figure step(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y) {
    return add(f, plot::series::step(x, y));
}


/**
 * Fluent error bars: append `series.errorbar(x, y, ylo, yhi)` to the targeted subplot.
 *
 * @param f the figure.
 * @param x the x positions.
 * @param y the central values.
 * @param ylo the lower whisker ends (absolute).
 * @param yhi the upper whisker ends (absolute).
 * @return a copy of @p f with the error bars appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0])
 * let y = ndarray.array([2.0, 3.0, 2.5])
 * let ylo = ndarray.array([1.7, 2.6, 2.2])
 * let yhi = ndarray.array([2.3, 3.4, 2.8])
 * let f = figure.new_figure()
 * f = figure.errorbar(f, x, y, ylo, yhi)   # -> whiskered points in the subplot
 * @endcode
 */
inline Figure errorbar(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y, ::cheatah::ndarray::basic_ndarray<double>& ylo, ::cheatah::ndarray::basic_ndarray<double>& yhi) {
    return add(f, plot::series::errorbar(x, y, ylo, yhi));
}


/**
 * Fluent heatmap: append `series.heatmap(z)` to the targeted subplot.
 *
 * @param f the figure.
 * @param z the row-major 2-D value grid.
 * @return a copy of @p f with the heatmap appended.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let flat = ndarray.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
 * let z = ndarray.reshape(flat, [2, 3])
 * let f = figure.new_figure()
 * f = figure.heatmap(f, z)   # -> the 2x3 grid, coloured by value
 * @endcode
 */
inline Figure heatmap(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& z) {
    return add(f, plot::series::heatmap(z));
}


/**
 * Fluent histogram: bin @p data with `plot.stats.histogram` and append the bars (touching, per
 * histogram convention).
 *
 * @param f the figure.
 * @param data the samples.
 * @param bins the bin count (clamped up to at least 1).
 * @return a copy of @p f with the histogram bars appended.
 * @complexity O(n + bins + figure).
 * @alloc the returned copy plus the histogram arrays.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let data = ndarray.array([1.0, 2.0, 2.0, 3.0, 3.0, 3.0, 4.0])
 * let f = figure.new_figure()
 * f = figure.hist(f, data, 4)   # -> touching histogram bars over 4 bins
 * @endcode
 */
inline Figure hist(builtins::Value auto&& f, ::cheatah::ndarray::basic_ndarray<double>& data, builtins::Value auto&& bins) {
    auto h = plot::stats::histogram(data, bins);
    auto s = plot::series::bar(h.centers, h.counts);
    s.width = 1.0;
    return add(f, s);
}


/**
 * Set the targeted subplot's title.
 *
 * @param f the figure.
 * @param t the title text.
 * @return a copy of @p f with the title set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * f = figure.title(f, "convergence")   # -> the current subplot is titled
 * @endcode
 */
inline Figure title(builtins::Value auto&& f, builtins::Value auto&& t) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.title = t;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Set the targeted subplot's x-axis label.
 *
 * @param f the figure.
 * @param s the label text.
 * @return a copy of @p f with the label set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * f = figure.xlabel(f, "epoch")   # -> the x axis reads "epoch"
 * @endcode
 */
inline Figure xlabel(builtins::Value auto&& f, builtins::Value auto&& s) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.x.label = s;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Set the targeted subplot's y-axis label.
 *
 * @param f the figure.
 * @param s the label text.
 * @return a copy of @p f with the label set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * f = figure.ylabel(f, "loss")   # -> the y axis reads "loss"
 * @endcode
 */
inline Figure ylabel(builtins::Value auto&& f, builtins::Value auto&& s) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.y.label = s;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Fix the targeted subplot's x limits (overriding auto).
 *
 * @param f the figure.
 * @param lo the low limit.
 * @param hi the high limit.
 * @return a copy of @p f with the limits set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * f = figure.xlim(f, 0.0, 10.0)   # -> x spans exactly [0, 10]; auto is overridden
 * @endcode
 */
inline Figure xlim(builtins::Value auto&& f, builtins::Value auto&& lo, builtins::Value auto&& hi) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.x.lo = lo;
    sp.x.hi = hi;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Fix the targeted subplot's y limits (overriding auto).
 *
 * @param f the figure.
 * @param lo the low limit.
 * @param hi the high limit.
 * @return a copy of @p f with the limits set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * f = figure.ylim(f, -1.0, 1.0)   # -> y pinned to [-1, 1]
 * @endcode
 */
inline Figure ylim(builtins::Value auto&& f, builtins::Value auto&& lo, builtins::Value auto&& hi) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.y.lo = lo;
    sp.y.hi = hi;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Set the targeted subplot's x-axis transform.
 *
 * @param f the figure.
 * @param s the Scale (linear() or log_scale()).
 * @return a copy of @p f with the transform set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * let s = figure.log_scale()
 * f = figure.xscale(f, s)   # -> decade ticks along x
 * @endcode
 */
inline Figure xscale(builtins::Value auto&& f, builtins::Value auto&& s) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.x.scale = s;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Set the targeted subplot's y-axis transform.
 *
 * @param f the figure.
 * @param s the Scale (linear() or log_scale()).
 * @return a copy of @p f with the transform set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * let s = figure.log_scale()
 * f = figure.yscale(f, s)   # -> log10 y; ticks land on decades
 * @endcode
 */
inline Figure yscale(builtins::Value auto&& f, builtins::Value auto&& s) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.y.scale = s;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Turn the targeted subplot's legend on or off (labeled series get entries when on).
 *
 * @param f the figure.
 * @param on true to draw the legend box.
 * @return a copy of @p f with the flag set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0])
 * let y = ndarray.array([1.0, 2.0, 4.0])
 * let f = figure.new_figure()
 * f = figure.line(f, x, y)
 * f = figure.legend(f, true)   # -> labeled series get legend entries
 * @endcode
 */
inline Figure legend(builtins::Value auto&& f, builtins::Value auto&& on) {
    auto g = f;
    auto sp = builtins::index(g.subplots, g.cur);
    sp.legend = on;
    g.subplots[g.cur] = sp;
    return g;
}


/**
 * Set the figure's pixel size.
 *
 * @param f the figure.
 * @param w the width in pixels (clamped up to at least 64).
 * @param h the height in pixels (clamped up to at least 64).
 * @return a copy of @p f with the size set.
 * @complexity O(figure).
 * @alloc the returned copy.
 * @systest systests/test_figure.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * let f = figure.new_figure()
 * f = figure.size(f, 1280, 720)   # -> a 1280x720 canvas
 * @endcode
 */
inline Figure size(builtins::Value auto&& f, builtins::Value auto&& w, builtins::Value auto&& h) {
    auto g = f;
    auto ww = w;
    if (ww < 64LL) {
        ww = 64LL;
    }
    auto hh = h;
    if (hh < 64LL) {
        hh = 64LL;
    }
    g.width = ww;
    g.height = hh;
    return g;
}


/// ABI/identity marker for the `figure` cheatah module: returns the module name.
///
/// Auto-emitted by purrc's library emitter. It is the concrete symbol that
/// anchors the module's signed static archive in opaque (source-hidden) builds.
/// @return the module name (`"figure"`).
inline const char* module_abi() noexcept { return "figure"; }

}  // namespace cheatah::figure

// Re-exported under the host namespace (--reexport cheatah::plot):
namespace cheatah::plot { namespace figure = ::cheatah::figure; }
