// Generated by purrc — do not edit.
// cheatah-deps: linalg math ndarray plot statistics
#pragma once
#include "cheatah.hpp"
#include "linalg.hpp"
#include "math.hpp"
#include "ndarray.hpp"
#include "plot.hpp"
#include "statistics.hpp"

/**
 * @file stats.hpp
 *
 * plot.stats — the numbers plotting needs shaped into plot-ready arrays: histogram binning, the
 * least-squares fit line, and error magnitudes.
 *
 * `import plot.stats as stats`.
 *
 * Honest REUSE of the stdlib, per the house rule: `linalg.lstsq` does the fitting,
 * `statistics` measures the spreads, and `plot.scale` supplies the widened data range — this
 * module only builds bins and evaluates the fitted line. Pure host math, no device.
 */
namespace cheatah::stats {

namespace builtins = ::cheatah::builtins;
namespace linalg = ::cheatah::linalg;
namespace math = ::cheatah::math;
namespace ndarray = ::cheatah::ndarray;
namespace plot = ::cheatah::plot;
namespace statistics = ::cheatah::statistics;

/**
 * A binned histogram: everything a bar mark needs to draw it.
 */
struct Hist {
    ::cheatah::ndarray::basic_ndarray<double> edges;
    ::cheatah::ndarray::basic_ndarray<double> centers;
    ::cheatah::ndarray::basic_ndarray<double> counts;
};

/**
 * Uniform-bin histogram of @p data over its widened range (plot.scale.data_range, so flat or
 * empty data still bins sanely). NaN values are skipped; values at or beyond the top edge land
 * in the last bin (the conventional right-inclusive tail).
 *
 * @param data the samples.
 * @param bins the bin count (clamped up to at least 1).
 * @return the Hist with edges, centers, and counts.
 * @complexity O(n + bins).
 * @alloc the three returned arrays.
 * @systest systests/test_stats.purr
 * @par Example
 * @code{.purr}
 * import plot.stats as stats
 * import ndarray
 * let data = ndarray.array([0.0, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0])
 * let h = stats.histogram(data, 4)   # -> h.centers/h.counts are bar-ready arrays
 * @endcode
 */
inline Hist histogram(::cheatah::ndarray::basic_ndarray<double>& data, builtins::Value auto&& bins) {
    auto b = bins;
    if ((b < 1LL)) {
        b = 1LL;
    }
    auto r = plot::scale::data_range(data);
    if ((r.lo != r.lo)) {
        r = plot::scale::Range({.lo = 0.0, .hi = 1.0});
    }
    auto step = builtins::truediv((r.hi - r.lo), builtins::to_float(b));
    auto edges = ndarray::zeros(std::vector{(b + 1LL)});
    for (long long i = 0; i < (b + 1LL); ++i) {
        edges[i] = (r.lo + (builtins::to_float(i) * step));
    }
    auto centers = ndarray::zeros(std::vector{b});
    for (long long i = 0; i < b; ++i) {
        centers[i] = (r.lo + ((builtins::to_float(i) + 0.5) * step));
    }
    auto counts = ndarray::zeros(std::vector{b});
    auto n = ndarray::size_of(data);
    for (long long i = 0; i < n; ++i) {
        auto v = builtins::index(data, i);
        if ((v == v)) {
            auto k = builtins::to_int(math::floor(builtins::truediv((v - r.lo), step)));
            if ((k < 0LL)) {
                k = 0LL;
            }
            if ((k >= b)) {
                k = (b - 1LL);
            }
            counts[k] = (builtins::index(counts, k) + 1.0);
        }
    }
    return Hist{.edges = static_cast<::cheatah::ndarray::basic_ndarray<double>>(edges), .centers = static_cast<::cheatah::ndarray::basic_ndarray<double>>(centers), .counts = static_cast<::cheatah::ndarray::basic_ndarray<double>>(counts)};
}


/**
 * The least-squares LINE through (x, y), evaluated at each x — pass it straight to a line mark
 * to overlay the trend (`figure.line(x, stats.fit(x, y))`). The solve is `linalg.lstsq` on the
 * [x, 1] design matrix; this function only assembles operands and evaluates the result.
 *
 * @param x the x positions.
 * @param y the y values (same length).
 * @return the fitted line's y at each @p x (fewer than 2 points: @p y unchanged — no line to fit).
 * @complexity O(n) assembly + the lstsq solve.
 * @alloc the design/rhs operands and the returned array.
 * @systest systests/test_stats.purr
 * @par Example
 * @code{.purr}
 * import plot.figure as figure
 * import plot.stats as stats
 * import ndarray
 * let x = ndarray.array([0.0, 1.0, 2.0, 3.0])
 * let y = ndarray.array([1.1, 2.9, 5.2, 6.8])
 * let trend = stats.fit(x, y)
 * let f = figure.new_figure()
 * f = figure.line(f, x, trend)   # -> the least-squares trend over the data
 * @endcode
 */
inline ::cheatah::ndarray::basic_ndarray<double> fit(::cheatah::ndarray::basic_ndarray<double>& x, ::cheatah::ndarray::basic_ndarray<double>& y) {
    auto n = ndarray::size_of(x);
    if ((n < 2LL)) {
        return y;
    }
    auto flat = ndarray::zeros(std::vector{(2LL * n)});
    for (long long i = 0; i < n; ++i) {
        flat[(2LL * i)] = builtins::index(x, i);
        flat[((2LL * i) + 1LL)] = 1.0;
    }
    auto design = ndarray::reshape(flat, std::vector{n, 2LL});
    auto rhs = ndarray::reshape(y, std::vector{n, 1LL});
    auto coef = ndarray::reshape(linalg::lstsq(design, rhs), std::vector{2LL});
    auto out = ndarray::zeros(std::vector{n});
    for (long long i = 0; i < n; ++i) {
        out[i] = ((builtins::index(coef, 0LL) * builtins::index(x, i)) + builtins::index(coef, 1LL));
    }
    return out;
}


/**
 * The standard error of the mean — the honest default magnitude for symmetric error bars
 * (`statistics.stdev` under the hood; this function only supplies the √n).
 *
 * @param data the samples.
 * @return stdev(@p data) / √n (0 when fewer than 2 samples — no spread to estimate).
 * @complexity O(n).
 * @alloc one transient list copy (statistics consumes lists).
 * @systest systests/test_stats.purr
 * @par Example
 * @code{.purr}
 * import plot.stats as stats
 * import ndarray
 * let data = ndarray.array([1.0, 2.0, 3.0, 4.0])
 * let e = stats.sem(data)   # -> 0.645...: stdev / sqrt(4), an errorbar magnitude
 * @endcode
 */
inline double sem(::cheatah::ndarray::basic_ndarray<double>& data) {
    auto n = ndarray::size_of(data);
    if ((n < 2LL)) {
        return 0.0;
    }
    std::vector<double> xs;
    for (long long i = 0; i < n; ++i) {
        builtins::append(xs, builtins::index(data, i));
    }
    return builtins::truediv(statistics::stdev(xs), math::sqrt(builtins::to_float(n)));
}


/// ABI/identity marker for the `stats` cheatah module: returns the module name.
///
/// Auto-emitted by purrc's library emitter. It is the concrete symbol that
/// anchors the module's signed static archive in opaque (source-hidden) builds.
/// @return the module name (`"stats"`).
inline const char* module_abi() noexcept { return "stats"; }

}  // namespace cheatah::stats

// Re-exported under the host namespace (--reexport cheatah::plot):
namespace cheatah::plot { namespace stats = ::cheatah::stats; }
